version: '3.9'

services:
  java_app:
    container_name: java_app
    image: shaukat/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://java_db:5432/postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
